version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomation_Prod252579Project
  gitServerName: RajniVCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: RajniVCTest
  gitUrl: https://github.com/vijetadixit
  gitUsername: Rajni25Aug
  gitBranch: Test2
